// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCpdkaPWXUI8kKYaI9-1RIk6OIXj4lE-7k',
    appId: '1:685145635402:android:7713ecee04f60c098944b3',
    messagingSenderId: '685145635402',
    projectId: 'flutter-instagram-clone-e8a1a',
    storageBucket: 'flutter-instagram-clone-e8a1a.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCGz52ESuIqXxX9-86wFL6L-C06kllPaq4',
    appId: '1:685145635402:ios:67d7009940f8249a8944b3',
    messagingSenderId: '685145635402',
    projectId: 'flutter-instagram-clone-e8a1a',
    storageBucket: 'flutter-instagram-clone-e8a1a.appspot.com',
    iosClientId: '685145635402-e54cm5jir6sjmgl4sb49kpogguh5q6ds.apps.googleusercontent.com',
    iosBundleId: 'com.example.instagramCloneRenew',
  );
}
